name: Check for Broken Links

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './**/*.html' './**/*.md'
          fail: true 